version: '3.8'

services:
  nodejs-app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  prometheus:
    build: ./prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  mongo-data:
  prometheus-data:
